import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/app/components/shared/Header";
import { ToastContainer } from "react-toastify";
import { Toaster } from "react-hot-toast";
import Providers from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: {
    default: "MediQueue",
    template: "%s | MediQueue",
  },
  description: "Generated by create next app",

};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full bg-white text-black dark:bg-gray-950 dark:text-white transition-colors duration-300">
         <Providers>

          <Header />

          {children}

          <ToastContainer
            position="top-right"
            autoClose={2000}
          />

          <Toaster
            position="top-right"
            reverseOrder={false}
          />

        </Providers>
      </body>
    </html>
  );
}
